FROM arm64v8/php:8.3-fpm

RUN apt-get update && apt-get install -y \
    unzip zip libzip-dev libpng-dev libjpeg-dev libonig-dev libcurl4-openssl-dev pkg-config libssl-dev \
    && docker-php-ext-install pdo pdo_mysql zip gd opcache \
    && pecl install redis && docker-php-ext-enable redis \
    && rm -rf /var/lib/apt/lists/*

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www
