version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: yaumi_app
    ports:
      - "9001:9000"
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - COMPOSER_ALLOW_SUPERUSER=1
    volumes:
      - ./docker-compose/php/php.prod.ini:/usr/local/etc/php/php.ini:ro
      - ./docker-compose/supervisor/conf.d:/etc/supervisor/conf.d
      - /opt/env/yaumi/.env.production:/var/www/.env:ro
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      # meilisearch:
      #   condition: service_healthy
    networks:
      - ryuuunet
    healthcheck:
      test: ["CMD", "pgrep", "php-fpm"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: yaumi_nginx
    restart: unless-stopped
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "8182:80"
    volumes:
      - /var/www:/var/www:ro
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - ryuuunet

  # meilisearch:
  #   image: getmeili/meilisearch:v1.5
  #   container_name: yaumi_meilisearch
  #   environment:
  #     - MEILI_MASTER_KEY=harry141312
  #     - MEILI_NO_ANALYTICS=true
  #     - MEILI_ENV=production
  #   ports:
  #     - "7700:7700"
  #   volumes:
  #     - meili_data:/meili_data
  #   networks:
  #     - ryuuunet
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 10
  #     start_period: 30s

  mysql:
    image: mysql:8.0
    container_name: yaumi_mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: yaumi_db
      MYSQL_ROOT_PASSWORD: harry141312
      MYSQL_PASSWORD: harry141312
      MYSQL_USER: harry
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker-compose/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - ryuuunet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pharry141312"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  redis:
    image: redis:alpine
    container_name: yaumi_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ryuuunet
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  ryuuunet:
    driver: bridge

volumes:
  dbdata:
  meili_data:
  redis_data:
