FROM arm64v8/php:8.3-fpm

RUN apt-get update && apt-get install -y \
    unzip zip libzip-dev libpng-dev libjpeg-dev \
    && docker-php-ext-install pdo pdo_mysql zip opcache gd \
    && rm -rf /var/lib/apt/lists/*

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www
