services:
  app:
    build:
      dockerfile: Dockerfile.prod
    ports:
      - "9001:9000"
    restart: unless-stopped
    environment:
      - APP_ENV=production
    volumes:
      - ./docker-compose/php/php.prod.ini:/usr/local/etc/php/php.ini:ro
      - /opt/env/yaumi/.env.production:/var/www/.env:ro
